export const srcBooks = [
    '/img/book1.jpg',
    '/img/bookProx.jpg',
    '/img/bookProx.jpg',
    '/img/bookProx.jpg',
    '/img/book5.jpg',
    '/img/bookProx.jpg',
    '/img/book7.jpg',
    '/img/book8.jpg',
    '/img/book1.jpg',
    '/img/bookProx.jpg',
    '/img/bookProx.jpg',
    '/img/bookProx.jpg',
    '/img/book5.jpg',
    '/img/bookProx.jpg',
    '/img/book7.jpg',
    '/img/book8.jpg',
    '/img/book1.jpg',
    '/img/bookProx.jpg',
    '/img/bookProx.jpg',
    '/img/bookProx.jpg',
    '/img/book5.jpg',
    '/img/bookProx.jpg',
    '/img/book7.jpg',
    '/img/book8.jpg',
  ];

  export const titleBooks = [
    'Neurociencia Cognitiva. (2ª Edición)',
    'Instrumentación quirúrgica: Principios y práctica. (8ª Edición)',
    'Perfil del Desarrollo Motor del Bebé: Infant Motor Profile (IMP)',
    'Fundamentos de Psiquiatría: Bases científicas para el manejo clínico.. (2ª Edición)',
    'Manejo de la Vía Aérea y Ventilación Mecánica',
    'Drogodependencias. (4ª Edición)',
    'Tratado de Esterilidad e Infertilidad Humanas',
    'Guía de Actuación en Urgencias. (6ª Edición)',
    'Neurociencia Cognitiva. (2ª Edición)',
    'Instrumentación quirúrgica: Principios y práctica. (8ª Edición)',
    'Perfil del Desarrollo Motor del Bebé: Infant Motor Profile (IMP)',
    'Fundamentos de Psiquiatría: Bases científicas para el manejo clínico.. (2ª Edición)',
    'Manejo de la Vía Aérea y Ventilación Mecánica',
    'Drogodependencias. (4ª Edición)',
    'Tratado de Esterilidad e Infertilidad Humanas',
    'Guía de Actuación en Urgencias. (6ª Edición)',
    'Neurociencia Cognitiva. (2ª Edición)',
    'Instrumentación quirúrgica: Principios y práctica. (8ª Edición)',
    'Perfil del Desarrollo Motor del Bebé: Infant Motor Profile (IMP)',
    'Fundamentos de Psiquiatría: Bases científicas para el manejo clínico.. (2ª Edición)',
    'Manejo de la Vía Aérea y Ventilación Mecánica',
    'Drogodependencias. (4ª Edición)',
    'Tratado de Esterilidad e Infertilidad Humanas',
    'Guía de Actuación en Urgencias. (6ª Edición)',
  ];
  
  export const authorBooks = [
    'MDiego Redolar Ripoll',
    'Joanna Kotcher Fuller',
    'Mijna Hadders-Algra, Kirsten R. Heineman',
    'Gabriel Rubio Valladolid, Guillermo Lahera Forteza, Roberto Rodríguez Jiménez,',
    'Eugenio Daniel Martínez Hurtado, María Luisa Mariscal Flores, Antonio García Rueda',
    'María Isabel Colado Megía, Magí Farré Albaladejo',
    'Enrique Pérez de la Blanca Cobos, José Antonio Domínguez Arroyo, Luis Rodríguez-Tabernero Martí',
    'Manuel José Vázquez Lima, José Ramón Casal Codesido',
    'MDiego Redolar Ripoll',
    'Joanna Kotcher Fuller',
    'Mijna Hadders-Algra, Kirsten R. Heineman',
    'Gabriel Rubio Valladolid, Guillermo Lahera Forteza, Roberto Rodríguez Jiménez,',
    'Eugenio Daniel Martínez Hurtado, María Luisa Mariscal Flores, Antonio García Rueda',
    'María Isabel Colado Megía, Magí Farré Albaladejo',
    'Enrique Pérez de la Blanca Cobos, José Antonio Domínguez Arroyo, Luis Rodríguez-Tabernero Martí',
    'Manuel José Vázquez Lima, José Ramón Casal Codesido',
    'MDiego Redolar Ripoll',
    'Joanna Kotcher Fuller',
    'Mijna Hadders-Algra, Kirsten R. Heineman',
    'Gabriel Rubio Valladolid, Guillermo Lahera Forteza, Roberto Rodríguez Jiménez,',
    'Eugenio Daniel Martínez Hurtado, María Luisa Mariscal Flores, Antonio García Rueda',
    'María Isabel Colado Megía, Magí Farré Albaladejo',
    'Enrique Pérez de la Blanca Cobos, José Antonio Domínguez Arroyo, Luis Rodríguez-Tabernero Martí',
    'Manuel José Vázquez Lima, José Ramón Casal Codesido',
  ];
  
  export const typeBooks = [
    'digital',
    'digital',
    'digital',
    'digital',
    'digital',
    'digital',
    'digital',
    'digital',
    'digital',
    'digital',
    'digital',
    'digital',
    'digital',
    'digital',
    'digital',
    'digital',
    'digital',
    'digital',
    'digital',
    'digital',
    'digital',
    'digital',
    'digital',
    'digital',
  ];
  export const type2Books = [
    'duo',
    'duo',
    'duo',
    'duo',
    'duo',
    'duo',
    'duo',
    'duo',
    'duo',
    'duo',
    'duo',
    'duo',
    'duo',
    'duo',
    'duo',
    'duo',
    'duo',
    'duo',
    'duo',
    'duo',
    'duo',
    'duo',
    'duo',
    'duo',
  ];
  export const initialBooks = [
    'NE',
    'NE',
    'N',
    'NE',
    'N',
    'NE',
    'N',
    'NE',
    'NE',
    'NE',
    'N',
    'NE',
    'N',
    'NE',
    'N',
    'NE',
    'NE',
    'NE',
    'N',
    'NE',
    'N',
    'NE',
    'N',
    'NE',
  ];
  export const fullTextBooks = [
    'Nueva edición',
    'Nueva edición',
    'novedad',
    'Nueva edición',
    'Nuevedad',
    'Nueva edición',
    'novedad',
    'Nueva edición',
    'Nueva edición',
    'Nueva edición',
    'novedad',
    'Nueva edición',
    'Nuevedad',
    'Nueva edición',
    'novedad',
    'Nueva edición',
    'Nueva edición',
    'Nueva edición',
    'novedad',
    'Nueva edición',
    'Nuevedad',
    'Nueva edición',
    'novedad',
    'Nueva edición'
  ];
  export const oldPriceBooks = ['92', '', '', '', '', '', '140', '60','92', '', '', '', '', '', '140', '60','92', '', '', '', '', '', '140', '60'];
  export const currentPriceBooks = ['880', 'prox', 'prox', 'prox', 'prox', 'prox', '590', '290','880', 'prox', 'prox', 'prox', 'prox', 'prox', '590', '290'];