import { FilterRealData } from './filterModelTemp';

export const allAuthorsMap = new Map<string, FilterRealData[]>([
  [
    'A',
    [
      { data: 'Aragonés Manzanares, Rocío', value: 'rocio-aragones-manzanares' },
      { data: 'Akesson, Elizabeth J.', value: 'digelizabeth-j-akessonital' },
      { data: 'Antonozzi, Italo', value: 'italo-antonozzi' },
      { data: 'Aguilera García, Concepción María', value: 'concepcion-maria-aguilera-garcia' },
      { data: 'Akiskal, Hagop', value: 'hagop-akiskal' },
      { data: 'Aragonés Manzanares, Rocío2', value: 'rocio-aragones-manzanares2' },
      { data: 'Akesson, Elizabeth J.', value: 'digelizabeth-j-akessonital' },
      { data: 'Antonozzi, Italo', value: 'italo-antonozzi' },
      { data: 'Aguilera García, Concepción María', value: 'concepcion-maria-aguilera-garcia' },
      { data: 'Akiskal, Hagop', value: 'hagop-akiskal' },
      { data: 'Aragonés Manzanares, Rocío', value: 'rocio-aragones-manzanares' },
      { data: 'Akesson, Elizabeth J.', value: 'digelizabeth-j-akessonital' },
      { data: 'Antonozzi, Italo', value: 'italo-antonozzi' },
      { data: 'Aguilera García, Concepción María', value: 'concepcion-maria-aguilera-garcia' },
      { data: 'Akiskal, Hagop', value: 'hagop-akiskal' },
      { data: 'Aragonés Manzanares, Rocío', value: 'rocio-aragones-manzanares' },
      { data: 'Akesson, Elizabeth J.', value: 'digelizabeth-j-akessonital' },
      { data: 'Antonozzi, Italo', value: 'italo-antonozzi' },
      { data: 'Aguilera García, Concepción María', value: 'concepcion-maria-aguilera-garcia' },
      { data: 'Akiskal, Hagop', value: 'hagop-akiskal' },
      { data: 'Aragonés Manzanares, Rocío', value: 'rocio-aragones-manzanares' },
      { data: 'Akesson, Elizabeth J.', value: 'digelizabeth-j-akessonital' },
      { data: 'Antonozzi, Italo', value: 'italo-antonozzi' },
      { data: 'Aguilera García, Concepción María', value: 'concepcion-maria-aguilera-garcia' },
      { data: 'Akiskal, Hagop', value: 'hagop-akiskal' },
    ],
  ],
  [
    'B',
    [
      { data: 'Bragonés Manzanares, Rocío', value: 'brocio-aragones-manzanares' },
      { data: 'Bkesson, Elizabeth J.', value: 'bigelizabeth-j-akessonital' },
    ],
  ],
]);
export const keyAuthorFilter = [
  'A',
  'B',
  'C',
  'D',
  'E',
  'F',
  'G',
  'H',
  'I',
  'J',
  'K',
  'L',
  'M',
  'N',
  'Ñ',
  'O',
  'P',
  'Q',
  'R',
  'S',
  'T',
  'U',
  'V',
  'W',
  'X',
  'Y',
  'Z',
];
